# This file contains development-specific overrides
#! hier befinden sich die anleitung wie das image ausgef√ºhrt werden soll
services:
  app:
    # This command enables Uvicorn's hot-reloading for development
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      # This volume enables live-syncing of your code for hot-reloading
      - .:/app